import useSWR from "swr"

export interface Topic {
  id: string
  text: string // renaming name to text per backend
  members: string[] // using array of usernames per backend
  created_at: string // using snake_case ISO string per backend
  status: "waiting" | "active" | "completed"
  resources: {
    youtube: { title: string; url: string }[]
    websites: { title: string; url: string }[]
  } | null
}

const TOPICS_KEY = "topics"
const CURRENT_USER_KEY = "currentUser"

// Initial topics data
const initialTopics: Topic[] = [
  {
    id: "1",
    text: "React Fundamentals",
    members: ["student1"],
    created_at: new Date().toISOString(),
    status: "waiting",
    resources: null,
  },
  {
    id: "2",
    text: "TypeScript Deep Dive",
    members: ["student2"],
    created_at: new Date().toISOString(),
    status: "active",
    resources: {
      youtube: [
        {
          title: "TypeScript Crash Course",
          url: "https://youtube.com/watch?v=example",
        },
      ],
      websites: [
        {
          title: "TypeScript Handbook",
          url: "https://www.typescriptlang.org/docs/handbook/intro.html",
        },
      ],
    },
  },
  {
    id: "3",
    text: "CSS Mastery",
    members: ["student3", "student4"],
    created_at: new Date().toISOString(),
    status: "waiting",
    resources: null,
  },
]

// Add user session management functions
export function setCurrentUser(email: string) {
  localStorage.setItem(CURRENT_USER_KEY, email)
}

export function getCurrentUser(): string | null {
  return localStorage.getItem(CURRENT_USER_KEY)
}

export function clearCurrentUser() {
  localStorage.removeItem(CURRENT_USER_KEY)
}

// Fetcher function for SWR
const fetcher = () => {
  const stored = localStorage.getItem(TOPICS_KEY)
  if (stored) {
    return JSON.parse(stored) as Topic[]
  }
  localStorage.setItem(TOPICS_KEY, JSON.stringify(initialTopics))
  return initialTopics
}

export function useTopics() {
  const { data: topics, mutate } = useSWR<Topic[]>(TOPICS_KEY, fetcher, {
    fallbackData: initialTopics,
    revalidateOnFocus: false,
  })

  // Ensure every topic has the required arrays and fields from the backend schema
  const safeTopics = (topics || []).map((topic) => ({
    ...topic,
    members: Array.isArray(topic.members) ? topic.members : [],
    resources: topic.resources || null,
  }))

  const addTopic = (text: string) => {
    const currentUser = getCurrentUser()
    const newTopic: Topic = {
      id: Date.now().toString(),
      text, // Use "text" field instead of "name"
      members: currentUser ? [currentUser] : [], // Creator is first member
      created_at: new Date().toISOString(),
      status: "waiting",
      resources: null, // Resources will be generated by backend
    }

    const updatedTopics = [...(topics || []), newTopic]
    localStorage.setItem(TOPICS_KEY, JSON.stringify(updatedTopics))
    mutate(updatedTopics, false)
  }

  const deleteTopic = (id: string) => {
    const updatedTopics = (topics || []).filter((topic) => topic.id !== id)
    localStorage.setItem(TOPICS_KEY, JSON.stringify(updatedTopics))
    mutate(updatedTopics, false)
  }

  const joinTopic = (id: string) => {
    const currentUser = getCurrentUser()
    if (!currentUser) {
      return { success: false, message: "Please log in to join a topic" }
    }

    const topic = (topics || []).find((t) => t.id === id)
    if (!topic) {
      return { success: false, message: "Topic not found" }
    }

    // Check if user has already joined
    if (topic.members.includes(currentUser)) {
      return { success: false, message: "You have already joined this topic" }
    }

    // Check if topic is full (max 5 members)
    if (topic.members.length >= 5) {
      return { success: false, message: "This topic is full" }
    }

    // Add user to members array
    const updatedTopics = (topics || []).map((topic) =>
      topic.id === id
        ? {
            ...topic,
            members: [...topic.members, currentUser],
          }
        : topic,
    )

    localStorage.setItem(TOPICS_KEY, JSON.stringify(updatedTopics))
    mutate(updatedTopics, false)
    return { success: true, message: "Successfully joined the topic!" }
  }

  return {
    topics: safeTopics,
    addTopic,
    deleteTopic,
    joinTopic,
  }
}
